### PR TITLE
Remove Forum Support link from left side menu

### LINKED ISSUE #481: Remove "Forum support" from menu
Screenshot 2022-09-20 at 12 19 59

### PR DESCRIPTION
**Pull request by mikozet**

### CODE REVIEW

**Review by llunaCreixent — COMMENTED** [review]
The `SUPPORT_URL` Value is also present in `Login.js` and `Welcome.js`.
Should we remove it from there also?

**Review by louilinn — CHANGES_REQUESTED** [review]
Remove support URL from all places, also the defintion of the variable

**Comment by mikozet** [comment]
> Remove support URL from all places, also the defintion of the variable

My assumptions is that we shouldn't remove "Forum support" link from other places like login page and welcome page?
They link to https://chat.joincircles.net/home

I asked Lucia on main task

**Comment by louilinn** [comment]
My understanding is that we never link to the rocket chat for support because noone maintains it as a support channel

**Comment by louilinn** [comment]
Finished this task for tomorrow's release as Miko is away. Updates based on answers in the related issue.

**Pull request merged**
