### PR TITLE
348 pink shadow at bottom while scrolling

### LINKED ISSUE #348: Pink shadow at bottom while scrolling
It should dissapear at the bottom of scrolling. We should display it also when user scrolls back from bottom to top.

### PR DESCRIPTION
**Pull request by mikozet**

### CODE REVIEW

**Review by louilinn — COMMENTED** [review]
Should it only show while scrolling? Or isn't it an indication that there is more information below to be scrolled?

Current behaviour:
loading page: no shadow (wrong I think) :warning: 
start scrolling: shadow (correct) :heavy_check_mark: 
reaching bottom: no shadow (correct) :heavy_check_mark: 
scrolling back up and reaching top: shadow (correct) :heavy_check_mark:

**Comment by mikozet** [comment]
Hi @louilinn 
It works for me when we load a page. Could you share more details? On which device you are, and which subpage maybe?

Zrzut ekranu 2022-06-9 o 12 32 17

Zrzut ekranu 2022-06-9 o 12 31 55

**Comment by louilinn** [comment]
I am on Chrome Version 96.0.4664.45 (Official Build) (64-bit) on debian 10
Personal dashboard

**Comment by louilinn** [comment]
Another problem on small screens: 
After (this PR):
Screenshot from 2022-06-09 14-50-19
Before (preview):
Screenshot from 2022-06-09 14-51-46

**Comment by louilinn** [comment]
Closes https://github.com/CirclesUBI/circles-myxogastria/issues/348

**Pull request merged**
