### PR TITLE
Update actions versions and use setup-node for caching

### PR DESCRIPTION
**Pull request by llunaCreixent**
Using the `.nvm` file works. However, caching the dependencies is not working. I suggest keep using the `actions/cache` action.

### CODE REVIEW

**Comment by llunaCreixent** [comment]
Check in the [Action](https://github.com/CirclesUBI/circles-myxogastria/actions/runs/4675900375/jobs/8281544972) the following log: `npm cache is not found`

**Comment by llunaCreixent** [comment]
Do you know how to cache the dependencies without using the `actions/cache` action? [Here](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) it says it's not necessary since you can configure the cache with `setup-node` action. We have 2 options:
1. Keep using `actions/cache`
2. Learns how to configure the cache through `setup-node` action

**Comment by llunaCreixent** [comment]
Perfect!
We accomplished option 2 (configure the cache through `setup-node` action).
You can check how the cache is found here: https://github.com/CirclesUBI/circles-myxogastria/actions/runs/4678146854/jobs/8286524579

All looks good can be reused for other repos

**Review by juanenrisley — APPROVED** [review]
👍🏿

**Review by louilinn — APPROVED** [review]

**Pull request merged**
