### PR TITLE
Add a loop for `core.token.transfer`

### PR DESCRIPTION
**Pull request by llunaCreixent**
Add a loop to update the transitive transfers steps when `core.token.transfer` fails due to data errors in the backend database.

### CODE REVIEW

**Comment by llunaCreixent** [comment]
You can test installing the new testing version core (https://github.com/CirclesUBI/circles-core/pull/119):
```
npm install @circleslluna/core@2.11.6-pre
```

**Comment by JacqueGM** [comment]
@mikozet  to review please use https://preview2.circles.garden/, so this PR will keep as a base main 
@llunaCreixent  to fix the conflicts

**Comment by llunaCreixent** [comment]
Node v14 doesn't work: `npm WARN tar ENOENT: no such file or directory`. So we use node v16.

**Review by JacqueGM — COMMENTED** [review]
Funcionaaaaaa!!!
It woooorks!!!

**Comment by llunaCreixent** [comment]
> Node v14 doesn't work: `npm WARN tar ENOENT: no such file or directory`. So we use node v16.

Fixed

**Review by louilinn — APPROVED** [review]
Great thank you!

**Pull request merged**
