### PR TITLE
Remove console errors on development

### LINKED ISSUE #709: Some errors on during local development which could be corrected
When open first time Activity page.
Screenshot from 2023-07-13 15-20-15

Clicking share profile link during wallet creation
Screenshot from 2023-07-13 13-52-26

'h4' element should not be inside of 'h2' element in Title of the popup
Screenshot from 2023-07-13 13-32-07

### PR DESCRIPTION
**Pull request by mikozet**

### CODE REVIEW

**Review by juanenrisley — APPROVED** [review]
👍🏿 LGTM lets see what @louilinn thinks

**Review by louilinn — COMMENTED** [review]
I still get this error:

```
Uncaught (in promise) Error: Cannot destructure property 'skipDedupe' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.
    at Gy (chunk-ZTBPADDD.js:24:37632)
    at chunk-ZTBPADDD.js:24:115595
```

Do you know why it is there?

We might as well fix all at once but also changes look fine and a quick check in UI I don't see any problem

**Comment by mikozet** [comment]
> I still get this error:
> 
> ```
> Uncaught (in promise) Error: Cannot destructure property 'skipDedupe' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.
>     at Gy (chunk-ZTBPADDD.js:24:37632)
>     at chunk-ZTBPADDD.js:24:115595
> ```
> 
> Do you know why it is there?
> 
> We might as well fix all at once but also changes look fine and a quick check in UI I don't see any problem

I do not see it, where do you see it and in which browser?

**Comment by louilinn** [comment]
Most likely it was a preview thing, sorry! You can ignore. I will merge it in the next release. 
Thank you Miko!

**Pull request merged**
