### PR TITLE
340 design onboarding oganisations should have white buttons not solid

### LINKED ISSUE #340: Design: Onboarding oganisations should have white buttons not solid
@triaslucia will update design material

### PR DESCRIPTION
**Pull request by mikozet**

### CODE REVIEW

**Comment by louilinn** [comment]
I can't find the design material for this. Can you link it in the issue or here?

**Comment by mikozet** [comment]
sure, it is here https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=5933%3A10429
@louilinn

**Comment by louilinn** [comment]
That link takes me to the app note update for time circles. Maybe a screenshot?

**Review by louilinn — APPROVED** [review]
Found it! Looks great :)

**Pull request merged**
