### PR TITLE
Organizational wallets

### LINKED ISSUE #170: Add and remove owners from an organisation

### PR DESCRIPTION
**Pull request by adzialocha**
This PR reintroduces the already developed "Organisational Wallets" feature which brings non-UBI collecting accounts into the Circles app.

The feature has been previously descoped before launch in October 2020. This PR revisits the former code and adds minor changes, fixes bugs and checks stability before finally launching.

**Bug fixes**

* [x] Balance in organizational wallet view is stuck in loading state
* [x] *"Selected address is not an option"* error when creating new organizational account
* [x] Token balance is `null` and breaking prefund step when opening app via `/organization` route directly
* [x] When returning from an organization to normal user profile the balance is stuck in loading state
* [x] Funding organization signup fails in relayer (PR: https://github.com/CirclesUBI/safe-relay-service/pull/46)
* [x] Can't trust users as organization (PR: CirclesUBI/circles-core#83)
* [x] Prefund transaction fails on production (PR: CirclesUBI/circles-core/pull/82)
* [x] Subgraph removes wrong owner (https://github.com/CirclesUBI/circles-subgraph/issues/31)
* [x] Clicking "Share payment link" in QR Code generator does not copy it into clipboard (Firefox, Desktop)
* [x] Removing yourself from the owners should redirect you directly to your own profile
* [x] After removing an owner, the list gets not updated correctly
* [x] Account without balance shows a spinning wheel forever in `BalanceDisplay`
* [x] SVG of tutorial contain encoded pngs
* [x] Double check which owner gets removed when user is connected to multiple addresses
* [x] Do not show "Create Shared Wallet" menu item in org dashboard 

Related: https://github.com/CirclesUBI/circles-subgraph/issues/38

Closes: #170, #169 and #168

### CODE REVIEW

**Comment by llunaCreixent** [comment]
This PR (https://github.com/CirclesUBI/circles-core/pull/83) should fix the "Can't trust users as organization" task.

**Comment by adzialocha** [comment]
> [CirclesUBI/circles-core#83](https://github.com/CirclesUBI/circles-core/pull/83)

Thanks, I'll refer to this in the PR description!

**Review by eminx — DISMISSED** [review]

**Comment by llunaCreixent** [comment]
Why is there in the `/search` view a button (top-right corner) that asks for using my camera?

**Comment by llunaCreixent** [comment]
Nice to have: [a way to see the "shared wallet" tutorial again](https://github.com/CirclesUBI/circles-myxogastria/issues/186).

**Comment by llunaCreixent** [comment]
Also, the menu item "Create Shared Wallet" shouldn't appear from an Org wallet. Or at least having a message informing the user that they need to do it from an non-org wallet.

**Review by llunaCreixent — DISMISSED** [review]
Looks great :) congrats!!

**Comment by adzialocha** [comment]
> Why is there in the /search view a button (top-right corner) that asks for using my camera?

Its starting the Camera for scanning a QR code! Maybe it needs a better icon? :-)

> Also, the menu item "Create Shared Wallet" shouldn't appear from an Org wallet. Or at least having a message informing the user that they need to do it from an non-org wallet.

Yeah, good catch! This we should fix before merging.

**Comment by llunaCreixent** [comment]
Related issues:
- https://github.com/CirclesUBI/circles-myxogastria/issues/188
- https://github.com/CirclesUBI/circles-myxogastria/issues/186

**Comment by llunaCreixent** [comment]
More related issues: https://github.com/CirclesUBI/circles-myxogastria/issues/191

**Pull request closed without merging**
