### PR TITLE
Add migration data functionality

### LINKED ISSUE #780: [epic] add profile migration opt-in form
## Scenario:

We need to transfer all garden profile data from the current servers (owned and maintained by Poetic Tech) to Gnosis (as per the announcement here: https://x.com/CirclesUBI/status/1785305562462494741).
As such we need to request permission from all garden users before any data is moved.

### Background:

"There will be a 3 months migration period where the users will be asked for their consent to migrate their email, username and photo to the new Circles infrastructure. If you accept the migration of your user profile, this will mean that your data will be transferred to the new Circles team. At the end of the migration period, all the data that is not transferred will be deleted from current databases. Your wallet, seed phrase, and CRC will not be deleted, and you will still be able to access to your wallet via [http://circles.garden/](http://circles.garden/)"

## Proposal:

- Add a message to the login page.
- Add content and a form to a new garden page called `profile-migrate` with a link to the Twitter post informing the user about the migration and requesting them to opt-in.
- Add a news item (in-app notification) in circles garden for all logged-in users (who would otherwise not see the msg on the login page) informing them about the migration. 

### Front-end:**
**Login page:**
- [x] Add a text message with the following content: `Circles Garden profile data is being migrated. You can read about this here: <https://x.com/CirclesUBI/status/1785305562462494741`> - (create short link using [[bit.ly](http://bit.ly/)](http://bit.ly/) or alternative)
- [x] Add the message: Please login and visit the 'profile-migrate' page to confirm your preference
- [x] suggested position: underneath the signup / login buttons

**Dashboard page:**
- [x] Add a text message with the following content: `Circles Garden profile data is being migrated. You can read about this here: <https://x.com/CirclesUBI/status/1785305562462494741`> - (create short link using [[bit.ly](http://bit.ly/)](http://bit.ly/) or alternative)
- [x] Add the message: Please visit the 'profile-migrate' page to confirm your preference
- [x] suggested position: underneath the balance display - above the button group

**Publish a news item:**
- [ ] Publish a new news item with the following content: `Circles Garden profile data is being migrated. You can read about this here: <https://x.com/CirclesUBI/status/1785305562462494741`> - (create short link using [[bit.ly](http://bit.ly/)](http://bit.ly/) or alternative)
- [ ] Add the message: Please visit the 'profile-migrate' page to confirm your preference.

**Profile migrate page:**
- [x] create a new page at `profile-migrate`
- [x] add a title `Migrate Your Profile`
- [x] add a text paragraph (with placeholder text for now)
- [x] display radio buttons with the label: `Do you consent to the migration of your profile data to the new Circles team?
- [x] option 1 : `No` (default)
- [x] option 2: `Yes`
- [x] `Submit` button
- [x] display a submission confirmation message: [TBD]

NOTE: it is important that we clearly explain the difference between profile data and an account (ie: editable database info vs blockchain)

**Back-end:**
- [ ]  add a database flag that stores the consent option for each user - at the end of August we will export the database but only for users that have answered `yes` to the consent question.

### PR DESCRIPTION
**Pull request by mikozet**
Closes #780

@shorn-gnosis this is how currently frontend and text content looks like. 
I still need to add API points and news item..

Feel free to comment and add changes

### Front-end:**
**Login page:**
- [x] Add a text message with the following content: `Circles Garden profile data is being migrated. You can read about this here: <https://x.com/CirclesUBI/status/1785305562462494741`> - (create short link using [[bit.ly](http://bit.ly/)](http://bit.ly/) or alternative)
- [x] Add the message: Please login and visit the 'profile-migrate' page to confirm your preference
- [x] suggested position: underneath the signup / login buttons

**Dashboard page:**
- [x] Add a text message with the following content: `Circles Garden profile data is being migrated. You can read about this here: <https://x.com/CirclesUBI/status/1785305562462494741`> - (create short link using [[bit.ly](http://bit.ly/)](http://bit.ly/) or alternative)
- [x] Add the message: Please visit the 'profile-migrate' page to confirm your preference
- [x] suggested position: underneath the balance display - above the button group

**Profile migrate page:**
- [x] create a new page at `profile-migrate`
- [x] add a title `Migrate Your Profile`
- [x] add a text paragraph (with placeholder text for now)
- [x] display radio buttons with the label: `Do you consent to the migration of your profile data to the new Circles team?
- [x] option 1 : `No` (default)
- [x] option 2: `Yes`
- [x] `Submit` button
- [x] display a submission confirmation message: [TBD]

Screenshot from 2024-06-28 14-15-28
Screenshot from 2024-06-28 14-15-02
Screenshot from 2024-06-28 14-14-52
Screenshot from 2024-06-28 15-24-05
Screenshot from 2024-06-28 15-24-25

### CODE REVIEW

**Comment by llunaCreixent** [comment]
The branch is deployed in staging (the circles-api also has the feature only in staging)

**Comment by llunaCreixent** [comment]
You can also check the notification in the news section:
https://staging.circles.garden/activities

**Comment by shorn-gnosis** [comment]
hey @mikozet and @llunaCreixent this all LGTM! happy to move this to staging or straight to production if you guys are fine with that too.

**Review by shorn-gnosis — DISMISSED** [review]
LGTM (i unfortunately can't test on chiado past the login screen due to some account error, but happy to move this to staging (or straight to production) - I'll explain about this other bug over email)

**Comment by mikozet** [comment]
> LGTM (i unfortunately can't test on chiado past the login screen due to some account error, but happy to move this to staging (or straight to production) - I'll explain about this other bug over email)

@shorn-gnosis @jaensen 
It is in staging currently: https://staging.circles.garden/
I can merge it to production - I just need approvals than I can merge and do release commit after

**Review by shorn-gnosis — APPROVED** [review]
utACK

**Pull request merged**
