### PR TITLE
 Add tutorial for Magic Words (Seed phrase) - Fix issue #107 

### LINKED ISSUE #107: Add tutorial for Magic Words (Seed phrase)

### PR DESCRIPTION
**Pull request by louilinn**
Closes issue #107

### CODE REVIEW

**Review by llunaCreixent — COMMENTED** [review]
This is great!
just one thing: the text of the 'What are "Magic Words"?' screen seems to be centered in the design from @triaslucia.

**Comment by louilinn** [comment]
> This is great!
> just one thing: the text of the 'What are "Magic Words"?' screen seems to be centered in the design from @triaslucia.

Yes, I ignored this :sweat_smile:  because I assumed it was a mistake from @triaslucia as I thought we want the same design on all dialogs (same as other dialogs in the app). Otherwise I can customize the component but I can of course do it. But it was a conscious choice from my side.

**Comment by llunaCreixent** [comment]
> > This is great!
> > just one thing: the text of the 'What are "Magic Words"?' screen seems to be centered in the design from @triaslucia.
> 
> Yes, I ignored this sweat_smile because I assumed it was a mistake from @triaslucia as I thought we want the same design on all dialogs (same as other dialogs in the app). Otherwise I can customize the component but I can of course do it. But it was a conscious choice from my side.

In that case I will approve :)

**Review by llunaCreixent — APPROVED** [review]

**Review by eminx — APPROVED** [review]
Looks all good to me :)

**Pull request merged**
