### PR TITLE
Add account data deletion functionality

### LINKED ISSUE #617: Allow deletion of user data - user interface
### User story:
The user wants to 
1. delete their user data themselves without sending an email request 
or
1. free up the username for another account

This happens mostly in connection to:
A wallet has not been deployed correctly
A wallet has been locked by the dead-man switch (90 day limit)

### Current situation / workaround
At the moment the username has to be replaced by a non-sense name which spams our username database and occupies usernames unnecessarily
Same with avatar and email.

### Suggested UI solution:
Add option in "Edit profile" (/edit) **and** "Settings" (/settings) to delete user data email, username and avatar all at once with an "Are you sure?" popup. 

The popup should explain that this will delete your avatar, username and email from the database and thus remove the connection between this data and your wallet/safe addresses that is on the blockchain. It will not delete your transaction messages or any transaction data on the blockchain. And maybe a link to information about what it means that your transactions are on the blockchain and that it cannot be deleted. (Pending article in handbook https://github.com/CirclesUBI/circles-handbook/issues/58)

### Considerations of allowing deletion of usernames (already concern for edit)
In activity log and when visiting the profile, the safe-address will be displayed instead of the old username for all other users.

### PR DESCRIPTION
**Pull request by mikozet**

### CODE REVIEW

**Comment by louilinn** [comment]
**Current text:**
>Do you want to delete your profile data?
>This action will delete your avatar, username and email from database - connection between those data and your wallet addresses on the blockchain.

>It will not delete your transaction messages or any transaction data on the blockchain. You may still recover your account in future using your seed phrase and edit your profile after that operation.

**Suggested text** 
>Do you want to delete your personal profile data?
>This action will delete your personal avatar, username and email from our databases. 

>This action will not delete any transaction data or trust interactions. Such data is stored on Gnosis blockchain and cannot be deleted by anyone. However, your blockchain transactions will no longer be traceable or linked to to your username or avatar.

>Upon deletion you can chose to log out. You may still recover your account in the future by using your magic words and edit your profile with a new profile data. If you do not log in within 90 days, your UBI payouts will stopped forever. It is also possible to continue to use circles.garden without an alias, avatar or email. 

>Please note that data deletion will not happen across wallets. You will have to do profile data deletion for your personal wallet and any shared wallets separately before logging out.

Another suggestion I have is to add a link to edit profile view in "Settings".

**Comment by llunaCreixent** [comment]
- Are we also going to delete the Notes from the transfers?
- I would call the "Gnosis blockchain" -> "Gnosis Chain", or even "Gnosis Chain blockchain. 
- Fixed a typo: "to to" -> "to"
- "will stopped" -> "will be stopped"

Here my proposed text:
>   Do you want to delete your personal profile data?
    This action will delete your personal avatar, username and email from our databases.

>   This action will not delete any transaction data or trust interactions. Such data is stored on Gnosis Chain blockchain and cannot be deleted by anyone. However, your blockchain transactions will no longer be traceable or linked to your username or avatar.

 >  Upon deletion you can chose to log out. You may still recover your account in the future by using your magic words and edit your profile with a new profile data. If you do not log in within 90 days, your UBI payouts will be stopped forever. It is also possible to continue to use circles.garden without an alias, avatar or email.

 >  Please note that data deletion will not happen across wallets. You will have to do profile data deletion for your personal wallet and any shared wallets separately before logging out.

**Comment by louilinn** [comment]
Updated suggestion:

We do not plan to delete the transfer notes, but I will discuss with product. In that case we should add this in a different task as it will involve much more work.

**Suggested text** 
>Do you want to delete your personal profile data?
>This action will delete your personal avatar, username and email from our databases. 

>This action will not delete any transaction data or trust interactions. Such data is stored on the Gnosis Chain blockchain and cannot be deleted by anyone. However, your blockchain transactions will no longer be traceable or linked to your username or avatar.

>Upon deletion you can chose to log out. You may still recover your account in the future by using your magic words and edit your profile with a new profile data. If you do not log in within 90 days, your UBI payouts will be stopped forever. It is also possible to continue to use circles.garden without an alias, avatar or email. 

>Please note that data deletion will not happen across wallets. You will have to do profile data deletion for your personal wallet and any shared wallets separately before logging out.

Thanks @lluna

**Comment by louilinn** [comment]
- [x] dialog
- [x] text
- [x] notification fail
- [x] notification success
- [x] call core / api to delete
- [x] add new profile picture generation? - not needed automatic
- [x] add to Settings
- [x] reroute after success to dashboard

**Comment by llunaCreixent** [comment]
The API is ready with 2 new endpoints (deployed already in staging and production): 
1. delete user entry
2. delete avatar image from storage (it'll only succeed if the image is not in the users db)

For the 2nd endpoint I suggest that it's used for the following 3 cases:
- when user edits profile img, and confirms the change
- when user deletes the user entry in db
- when the user uploads many images through the app but doesn't confirm so save it for their profile.

**Comment by llunaCreixent** [comment]
Also, should the delete option be available even when the Safe is not deployed (i.e. circles account not created)??

**Comment by llunaCreixent** [comment]
> Also, should the delete option be available even when the Safe is not deployed (i.e. circles account not created)??

As it is implemented now, only the owner of the profile can delete the profile entry, and it has to prove the ownership of the safe address through the subgraph. The subgraph will only register ownership of safes once they are deployed.

**Comment by llunaCreixent** [comment]
The core method for deleting the user will be available with `core.user.delete`
Check the PR https://github.com/CirclesUBI/circles-core/pull/240

**Comment by louilinn** [comment]
> > Also, should the delete option be available even when the Safe is not deployed (i.e. circles account not created)??
> 
> As it is implemented now, only the owner of the profile can delete the profile entry, and it has to prove the ownership of the safe address through the subgraph. The subgraph will only register ownership of safes once they are deployed.

So nothing else is possible? Without a lot of changes?

**Comment by llunaCreixent** [comment]
> > > Also, should the delete option be available even when the Safe is not deployed (i.e. circles account not created)??
> > 
> > 
> > As it is implemented now, only the owner of the profile can delete the profile entry, and it has to prove the ownership of the safe address through the subgraph. The subgraph will only register ownership of safes once they are deployed.
> 
> So nothing else is possible? Without a lot of changes?

For allowing users that haven't deployed their safe to remove the profile, we could verify on those cases the future ownership of the Safe by asking the relayer db

**Comment by louilinn** [comment]
We could consider adding a route to Edit profile in settings too?

**Comment by louilinn** [comment]
Needs fixing: 
- [x] "I'll do this later" button should switch to Continue upon avatar upload in onboarding

**Comment by louilinn** [comment]
new FAQ link https://joincircles.net/faq/profile-data-deletion/

**Comment by louilinn** [comment]
Problem remaining: avatar in onboarding step is wrong after avatar upload

**Comment by louilinn** [comment]
Behaviour for documentation
### Edit profile
- when **saving** a new profile, old profile is deleted
- when cancelling, current unsaved upload is deleted from aws
- when uploading a second new image, previously unsaved upload is deleted from aws
- when closing the window or quitting the page, an unsaved upload is still saved to aws (not easily fixed) but not associated with any account *

### Delete profile
- old avatar deleted from aws

### Onboarding / Account creation
- when uploading a second new image, previously unsaved upload is deleted from aws
- quitting onboarding does not delete the upload from aws (not easily fixed) but not associated with any account *

\* unassociated pictures will be deleted periodicly from aws instead

**Review by louilinn — APPROVED** [review]
Tested

**Pull request merged**
