### PR TITLE
Link to icons for adding to mobile homescreens

### PR DESCRIPTION
**Pull request by rosano**
This looks nicer than the cropped screenshot of the page on iOS.

The URLs might not be ideal (taken from https://joincircles.net), but I wasn't sure if it would be better to copy the images into this repository as everything seems to be SVG; happy to do that if desired.

### CODE REVIEW

**Comment by louilinn** [comment]
Thank you for your contribution! We will review this as soon as we have time

**Comment by louilinn** [comment]
@rosano Hey I tried to rebase this somehow, maybe you can do it properly and push again?
If you don't have time I'll just do this in a new PR. Sorry for the mess :smile_cat:

**Comment by rosano** [comment]
@louilinn okay here is #441, although I think it should be easy to rebase and merge from github.com

**Comment by louilinn** [comment]
https://github.com/CirclesUBI/circles-myxogastria/pull/441 Merged here

**Pull request closed without merging**
