### PR TITLE
Opening dashboard doesnt move content

### LINKED ISSUE #339: Opening left menu should not push the page to the right
It should appear on top of the page

### PR DESCRIPTION
**Pull request by mikozet**
Closes https://github.com/CirclesUBI/circles-myxogastria/issues/339

### CODE REVIEW

**Review by louilinn — COMMENTED** [review]
These changes does not fix this problem when I test it in the browser :(

**Comment by mikozet** [comment]
Hi @louilinn could you share more details? Maybe which browser do you use?
It works for me on Chrome like below in attached image..
Zrzut ekranu 2022-06-9 o 12 40 13

**Comment by louilinn** [comment]
Screenshot from 2022-06-09 12-54-08
Screenshot from 2022-06-09 12-54-18
I am on Chrome Version 96.0.4664.45 (Official Build) (64-bit) on debian 10

**Comment by louilinn** [comment]
Screenshot from 2022-06-09 12-56-43

**Pull request merged**
