### PR TITLE
Update AppNotificationInfo

### PR DESCRIPTION
**Pull request by mikozet**

### CODE REVIEW

**Comment by louilinn** [comment]
Can you provide some context of this PR since there is no issue to explain the work you have done? Also when you want these changes to take affect
(please do so in the top comment)

**Comment by louilinn** [comment]
Can you provide some context of this PR since there is no issue to explain the work you have done?

**Comment by mikozet** [comment]
> Can you provide some context of this PR since there is no issue to explain the work you have done?

Yes, it was updates coresponding to changed design. New version available here:
https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A26250

**Comment by mikozet** [comment]
I am closing it it is obsolete now

**Pull request closed without merging**
