### PR TITLE
Update migrate profile text in locales

### PR DESCRIPTION
**Pull request by llunaCreixent**
We need to add a link to the page. Probably not useful before login, so just in the text of the dashboard.

### CODE REVIEW

**Comment by mikozet** [comment]
for news item content would look like this:


```
<span class="info-text">
  <p>Circles Garden profile data is being migrated. You can read about this 
    <a href="https://bit.ly/3W1il2M" target="_blank" rel="noopener noreferrer">here</a>.
  </p>
  <p>Please visit <a href="https://circles.garden/profile-migrate" rel="noopener noreferrer">Migrate Your Profile</a> from the menu to confirm your preference.</p>
</span>
```

**Comment by mikozet** [comment]
it is deployed on stagging currently

**Comment by llunaCreixent** [comment]
> for news item content would look like this:
> 
> ```
> <span class="info-text">
>   <p>Circles Garden profile data is being migrated. You can read about this 
>     <a href="https://bit.ly/3W1il2M" target="_blank" rel="noopener noreferrer">here</a>.
>   </p>
>   <p>Please visit <a href="https://circles.garden/profile-migrate" rel="noopener noreferrer">Migrate Your Profile</a> from the menu to confirm your preference.</p>
> </span>
> ```

Can we have a relative link to the 'migrate-profile' page?

**Review by llunaCreixent — COMMENTED** [review]
Cool! LGTM!
I've updated the news in prod

**Review by Werborg55 — APPROVED** [review]

**Pull request merged**
